name: old_cont
description: App Flutter Old-cont

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.18.0
  drift_sqflite: ^2.4.2
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
dev_dependencies:
  drift_dev: ^2.18.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
